name: Deploy docs

on:
  push:
    tags: ["*"]          

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
